### ISSUE TITLE
Installing using expo and latest React Native throw error

### ISSUE THREAD

**Issue by ecerichter** [kevinstumpf/react-native-signature-pad#78]
Hi!
Trying to install using latest React Native throws the following exception:

PS C:\Users\richter\Documents\projects\AssinaturaRomaneio\AssinaturaRomaneioUI> npx expo install react-native-signature-pad                      
› Installing 1 other package using npm
> npm install --save react-native-signature-pad
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: assinaturaromaneioui@1.0.0
npm error Found: react@18.3.1
npm error node_modules/react
npm error   react@"18.3.1" from the root project
npm error
npm error Could not resolve dependency:
npm error peer react@"^16.8.4" from react-native-signature-pad@0.1.2
npm error node_modules/react-native-signature-pad
npm error   react-native-signature-pad@"^0.1.2" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error C:\Users\richter\AppData\Local\npm-cache\_logs\2024-12-16T13_19_08_311Z-eresolve-report.txt
npm error A complete log of this run can be found in: C:\Users\richter\AppData\Local\npm-cache\_logs\2024-12-16T13_19_08_311Z-debug-0.log
Error: npm install --save react-native-signature-pad exited with non-zero code: 1
Error: npm install --save react-native-signature-pad exited with non-zero code: 1
    at ChildProcess.completionListener (C:\Users\richter\Documents\projects\AssinaturaRomaneio\AssinaturaRomaneioUI\node_modules\@expo\spawn-async\build\spawnAsync.js:42:23)
    at Object.onceWrapper (node:events:639:26)
    at ChildProcess.emit (node:events:524:28)
    at cp.emit (C:\Users\richter\Documents\projects\AssinaturaRomaneio\AssinaturaRomaneioUI\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1101:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5)
    ...
    at spawnAsync (C:\Users\richter\Documents\projects\AssinaturaRomaneio\AssinaturaRomaneioUI\node_modules\@expo\spawn-async\build\spawnAsync.js:7:23)
    at NpmPackageManager.runAsync (C:\Users\richter\Documents\projects\AssinaturaRomaneio\AssinaturaRomaneioUI\node_modules\@expo\package-manager\build\node\BasePackageManager.js:41:42)
    at C:\Users\richter\Documents\projects\AssinaturaRomaneio\AssinaturaRomaneioUI\node_modules\@expo\package-manager\build\node\NpmPackageManager.js:37:20
    at C:\Users\richter\Documents\projects\AssinaturaRomaneio\AssinaturaRomaneioUI\node_modules\@expo\package-manager\build\utils\spawn.js:19:34
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

Result of npm ls:

PS C:\Users\richter\Documents\projects\MyApp\MyAppUI> npm ls
assinaturaromaneioui@1.0.0 C:\Users\richter\Documents\projects\MyApp\MyAppUI
├── @babel/core@7.26.0
├── @types/react@18.3.17
├── expo-status-bar@2.0.0
├── expo@52.0.18
├── react-native-webview@13.12.5
├── react-native@0.76.5
├── react@18.3.1
└── typescript@5.7.2

Anything I'm missing? Can I help upgrade dependencies?

Thanks,

ER

**Comment by Jahanzeb009** [comment]
try --force flag

`npm i <library-name> --force`
